import { memo } from 'react';

interface SvgCanvasProps {
  svg: string;
  className?: string;
  /** Fit the SVG to the container width instead of using its intrinsic size. */
  fluid?: boolean;
}

/**
 * Mounts an engine-produced SVG document.
 *
 * The markup is fully generated by `src/engine` — colours come from
 * `<input type="color">` and every path is re-serialized by our own
 * parser, so no third-party markup reaches the DOM.
 */
export const SvgCanvas = memo(function SvgCanvas({
  svg,
  className = '',
  fluid = false,
}: SvgCanvasProps) {
  return (
    <div
      className={
        `${className} min-h-0 min-w-0 [&>svg]:block ` +
        (fluid
          ? 'h-full w-full [&>svg]:h-full [&>svg]:w-full [&>svg]:max-h-full [&>svg]:max-w-full'
          : '[&>svg]:max-w-full')
      }
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
});
